#! /bin/bash

if [[ -z $1 ]]; then
    echo -e "You must pass in a commit message"
    exit
fi

echo "Push CloudNotes on $HOSTNAME"
./push "$1"
echo "Push GitIo on $HOSTNAME"
./send "$1"
ssh -t aws bin/pull-key-repos
echo "done."
