#! /bin/bash

function message {
    echo
    echo =======================
    echo "$1"
    echo =======================
    echo
}

if [[ -z $1 ]]; then
    echo -e "You must pass in a commit message"
    exit
fi

message "Push CloudNotes on $HOSTNAME"
./push "$1"

message "Push GitIo on $HOSTNAME"
./send "$1"

message "Switching to AWS"

ssh -t aws bin/pull-key-repos
echo "done."
