#! /bin/bash
DESTDIR="$HOME/Git/charliecalvert.github.io/"

if [ -z "$SSH_AUTH_SOCK" ] ; then
    eval `ssh-agent`
fi

ssh-add $ELF_SSH_DIR/Home-2016-03

if [[ -z $1 ]]; then
    echo -e "You must pass in a commit message"
    exit
fi

function git-commit() {
	cd $DESTDIR
	pwd
	git add .
	git commit -m "$1 $NOW"
	git push
}

git-commit $1
