<html>
<head>
<title>Sample PHP File</title>
<link href="../libs/css/style2.css" rel="stylesheet" title="style2" type="text/css" />
</head>
<body>
<h1>PHP Sample File</h1>

<?php 
 Print "<p>This text is generated by the PHP script engine, not by a plain HTML file.</p>";
 Print "<p>If you right click and choose View Source you will not see PHP code, but rather the HTML that the PHP generates.</p>";
 Print "<p>Click <a href='../downloads/Php/sample_php.zip'>here</a> to download a copy of this file. The file you download may not match this file exactly, as I frequently update file on the site.</p>";
 Print "<p>Here are some bits of text generated by calls to the PHP script engine:</p>";
 Print "<p>" . $_SERVER['HTTP_USER_AGENT'] . "</p>";
 Print "<p>" . $_SERVER['GATEWAY_INTERFACE'] . "</p>";
 Print $_SERVER['PHP_SELF'];
 ?> 
 
 
 

<pre class="code">
<?php
 PRINT "<p>This file last modified: " . date ("F d Y H:i:s.", getlastmod()) . "</p>";
?>
</pre>
 </body>
 </html>