<div id="container">
	<header>
		<div class="navButton" onclick="elvenware.toggleMenu()">
			Menu</div>
		<h1>Charlie Calvert on Elvenware</h1>
		<h2>Writing Code and Prose on Computers</h2>
	</header>
	<nav>
		<div id="accordion00">
		<h2 class="navSection01">Core Code</h2>
			<ul>
				<li><a href="../development/index.html">Strongly Typed</a></li>
				<li><a href="../development/web/index.html">Web &amp; Scripts</a></li>
				<li><a href="index.html">Software Design</a></li>
			</ul>
		
			<h2 class="navSection02">OS and Tools</h2>
			<ul>
				<li><a href="../os/index.html">OS</a></li>
				<li><a href="../development/database/index.html">Database</a></li>
				<li><a href="../books/index.html">My Writing</a></li>
			</ul>
			
		
			<h2 class="navSection03">Art</h2>
			<ul>
				<li><a href="../Art/index.html">Poems &amp; Photos</a></li>
				<li><a href="../books/reading/index.html">Book Reviews</a></li>
				<li><a href="../spirit/index.html">Spiritual</a></li>
			</ul>
			<h2 class="navSection04">Links</h2>
			<ul>
				<li><a href="../links.html">My Links</a></li>
				<li><a href="http://www.falafel.com/">Falafel</a></li>
				<li><a href="http://sourceforge.net/projects/elvenware/">Sourceforge</a></li>
			</ul>
		</div>
	</nav>
