<ol>
	<li><a href="/charlie/development/web/Server/SetupAWebSite.html">Install IIS and/or Setup a WebSite</a></li>
	<li><a href="/charlie/development/web/Server/Apache.html">Apache</a></li>
	<li><a href="/charlie/development/web/Server/PublishPage.html">Publish a Web Page</a></li>
	<li><a href="/charlie/development/web/Server/IisSecurity.html">IIS Security</a></li>
	<li><a href="/charlie/development/web/Server/ServerSideIncludes.html">Turn on Server Side Includes in IIS</a></li>
	<li><a href="/charlie/development/web/Server/UrlRewrites.html">URL ReWrites</a></li>
	<li><a href="/charlie/development/web/Server/NetworkFacts.html">Network Facts</a></li>
	<li><a href="/charlie/development/web/Server/HttpBasics.html">HTTP Basics</a></li>
	<li><a href="/charlie/development/web/Server/HttpStatusCodes.html">HTTP Status Codes</a></li>
</ol>
