cp /home/ubuntu/Git/CloudNotes/Assignments/FirebaseStarter.md /home/ubuntu/Git/CloudNotes/Assignments/Firebase/FirebaseStarter.md
cp /home/ubuntu/Git/CloudNotes/Assignments/FirebaseData.md /home/ubuntu/Git/CloudNotes/Assignments/Firebase/FirebaseData.md
cp /home/ubuntu/Git/CloudNotes/Assignments/FirebaseFinalPrep.md /home/ubuntu/Git/CloudNotes/Assignments/Firebase/FirebaseFinalPrep.md
cp /home/ubuntu/Git/CloudNotes/Assignments/FirebaseLogin.md /home/ubuntu/Git/CloudNotes/Assignments/Firebase/FirebaseLogin.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressRoutesSolar.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressRoutesSolar.md
cp /home/ubuntu/Git/CloudNotes/Assignments/SinglePageExpress.md /home/ubuntu/Git/CloudNotes/Assignments/Express/SinglePageExpress.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressJQueryNumbers.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressJQueryNumbers.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressRoutesSolarTests.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressRoutesSolarTests.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MapExpress.md /home/ubuntu/Git/CloudNotes/Assignments/Express/MapExpress.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressBasics.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressBasics.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressSessionMaster.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressSessionMaster.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MangoExpress.md /home/ubuntu/Git/CloudNotes/Assignments/Express/MangoExpress.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressMiddlewareBasics.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressMiddlewareBasics.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressSessionBasics.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressSessionBasics.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressPagesAndMixins.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressPagesAndMixins.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressJQuery.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressJQuery.md
cp /home/ubuntu/Git/CloudNotes/Assignments/BashExpressScript.md /home/ubuntu/Git/CloudNotes/Assignments/Express/BashExpressScript.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressRoutes.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressRoutes.md
cp /home/ubuntu/Git/CloudNotes/Assignments/NodeExpressMongo01.md /home/ubuntu/Git/CloudNotes/Assignments/Express/NodeExpressMongo01.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressMiddlewareUser.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressMiddlewareUser.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressSessionCouch.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressSessionCouch.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressRoutesSolarCleaner.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressRoutesSolarCleaner.md
cp /home/ubuntu/Git/CloudNotes/Assignments/JasmineExpressMock.md /home/ubuntu/Git/CloudNotes/Assignments/Express/JasmineExpressMock.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressRoutesSolarDeeper.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressRoutesSolarDeeper.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ExpressRoutesSolarRefactor.md /home/ubuntu/Git/CloudNotes/Assignments/Express/ExpressRoutesSolarRefactor.md
cp /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy04.md /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy/CodeAcademy04.md
cp /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy07.md /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy/CodeAcademy07.md
cp /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademyGit02.md /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy/CodeAcademyGit02.md
cp /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy02.md /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy/CodeAcademy02.md
cp /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy03.md /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy/CodeAcademy03.md
cp /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademyGit03.md /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy/CodeAcademyGit03.md
cp /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademyGit04.md /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy/CodeAcademyGit04.md
cp /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademyGit01.md /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy/CodeAcademyGit01.md
cp /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy05.md /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy/CodeAcademy05.md
cp /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy06.md /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy/CodeAcademy06.md
cp /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy01.md /home/ubuntu/Git/CloudNotes/Assignments/CodeAcademy/CodeAcademy01.md
cp /home/ubuntu/Git/CloudNotes/Assignments/HerokuStarter.md /home/ubuntu/Git/CloudNotes/Assignments/Heroku/HerokuStarter.md
cp /home/ubuntu/Git/CloudNotes/Assignments/HerokuReactStarter.md /home/ubuntu/Git/CloudNotes/Assignments/Heroku/HerokuReactStarter.md
cp /home/ubuntu/Git/CloudNotes/Assignments/GruntSmokeTest01.md /home/ubuntu/Git/CloudNotes/Assignments/SmokeTests/GruntSmokeTest01.md
cp /home/ubuntu/Git/CloudNotes/Assignments/GruntSmokeTest03.md /home/ubuntu/Git/CloudNotes/Assignments/SmokeTests/GruntSmokeTest03.md
cp /home/ubuntu/Git/CloudNotes/Assignments/GruntSmokeTest02.md /home/ubuntu/Git/CloudNotes/Assignments/SmokeTests/GruntSmokeTest02.md
cp /home/ubuntu/Git/CloudNotes/Assignments/GitHubApi.md /home/ubuntu/Git/CloudNotes/Assignments/Git/GitHubApi.md
cp /home/ubuntu/Git/CloudNotes/Assignments/GitDualRepos.md /home/ubuntu/Git/CloudNotes/Assignments/Git/GitDualRepos.md
cp /home/ubuntu/Git/CloudNotes/Assignments/GitBranchProject.md /home/ubuntu/Git/CloudNotes/Assignments/Git/GitBranchProject.md
cp /home/ubuntu/Git/CloudNotes/Assignments/NewGitBucket.md /home/ubuntu/Git/CloudNotes/Assignments/Git/NewGitBucket.md
cp /home/ubuntu/Git/CloudNotes/Assignments/GitBranchBasics.md /home/ubuntu/Git/CloudNotes/Assignments/Git/GitBranchBasics.md
cp /home/ubuntu/Git/CloudNotes/Assignments/GitBranchWeeks.md /home/ubuntu/Git/CloudNotes/Assignments/Git/GitBranchWeeks.md
cp /home/ubuntu/Git/CloudNotes/Assignments/LinuxServerBasics.md /home/ubuntu/Git/CloudNotes/Assignments/Linux/LinuxServerBasics.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MongoMark.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/MongoMark.md
cp /home/ubuntu/Git/CloudNotes/Assignments/AngularMongoDbTest.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/AngularMongoDbTest.md
cp /home/ubuntu/Git/CloudNotes/Assignments/AngularMongooseRefine.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/AngularMongooseRefine.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MongooseBasics.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/MongooseBasics.md
cp /home/ubuntu/Git/CloudNotes/Assignments/AngularMongoDbCrud.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/AngularMongoDbCrud.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MongooseComments.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/MongooseComments.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ServerSaveMongo.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/ServerSaveMongo.md
cp /home/ubuntu/Git/CloudNotes/Assignments/AngularMongooseOnePage.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/AngularMongooseOnePage.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MongoStarter.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/MongoStarter.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MongooseMtgSets.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/MongooseMtgSets.md
cp /home/ubuntu/Git/CloudNotes/Assignments/AngularMongoDbStarter.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/AngularMongoDbStarter.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MongooseRoutes.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/MongooseRoutes.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MongooseSignInComment.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/MongooseSignInComment.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MongooseSubDocuments.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/MongooseSubDocuments.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MongooseEditor.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/MongooseEditor.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MongooseMagic.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/MongooseMagic.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MongooseSignIn.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/MongooseSignIn.md
cp /home/ubuntu/Git/CloudNotes/Assignments/NodeExpressMongo01.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/NodeExpressMongo01.md
cp /home/ubuntu/Git/CloudNotes/Assignments/MongoLabBasics.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/MongoLabBasics.md
cp /home/ubuntu/Git/CloudNotes/Assignments/AngularMongooseBasics.md /home/ubuntu/Git/CloudNotes/Assignments/Mongo/AngularMongooseBasics.md
cp /home/ubuntu/Git/CloudNotes/Assignments/Ec2SiteDeploy.md /home/ubuntu/Git/CloudNotes/Assignments/Aws/Ec2SiteDeploy.md
cp /home/ubuntu/Git/CloudNotes/Assignments/Ec2EndOfQuarter.md /home/ubuntu/Git/CloudNotes/Assignments/Aws/Ec2EndOfQuarter.md
cp /home/ubuntu/Git/CloudNotes/Assignments/Ec2CloudOnly.md /home/ubuntu/Git/CloudNotes/Assignments/Aws/Ec2CloudOnly.md
cp /home/ubuntu/Git/CloudNotes/Assignments/Ec2MarkdownToHtml.md /home/ubuntu/Git/CloudNotes/Assignments/Aws/Ec2MarkdownToHtml.md
cp /home/ubuntu/Git/CloudNotes/Assignments/LampBootstrap.md /home/ubuntu/Git/CloudNotes/Assignments/Aws/LampBootstrap.md
cp /home/ubuntu/Git/CloudNotes/Assignments/Ec2Checklist.md /home/ubuntu/Git/CloudNotes/Assignments/Aws/Ec2Checklist.md
cp /home/ubuntu/Git/CloudNotes/Assignments/Ec2Provision.md /home/ubuntu/Git/CloudNotes/Assignments/Aws/Ec2Provision.md
cp /home/ubuntu/Git/CloudNotes/Assignments/Ec2GetStarted.md /home/ubuntu/Git/CloudNotes/Assignments/Aws/Ec2GetStarted.md
cp /home/ubuntu/Git/CloudNotes/Assignments/Ec2RunElvenSite.md /home/ubuntu/Git/CloudNotes/Assignments/Aws/Ec2RunElvenSite.md
cp /home/ubuntu/Git/CloudNotes/Assignments/LampMarkdown.md /home/ubuntu/Git/CloudNotes/Assignments/Aws/LampMarkdown.md
cp /home/ubuntu/Git/CloudNotes/Assignments/Ec2DataHunterFinalPrep.md /home/ubuntu/Git/CloudNotes/Assignments/Aws/Ec2DataHunterFinalPrep.md
cp /home/ubuntu/Git/CloudNotes/Assignments/ApacheHtml.md /home/ubuntu/Git/CloudNotes/Assignments/Aws/ApacheHtml.md
cp /home/ubuntu/Git/CloudNotes/Assignments/Ec2GitHtmlPictures.md /home/ubuntu/Git/CloudNotes/Assignments/Aws/Ec2GitHtmlPictures.md
cp /home/ubuntu/Git/CloudNotes/Assignments/NpmUtilities.md /home/ubuntu/Git/CloudNotes/Assignments/Npm/NpmUtilities.md
cp /home/ubuntu/Git/CloudNotes/Assignments/NpmAllInclusive.md /home/ubuntu/Git/CloudNotes/Assignments/Npm/NpmAllInclusive.md
cp /home/ubuntu/Git/CloudNotes/Assignments/NpmPublishing.md /home/ubuntu/Git/CloudNotes/Assignments/Npm/NpmPublishing.md