<ul>
	<li><a href="/charlie/development/web/JavaScript/index.html">JavaScript and jQuery Page</a></li>
	<li><a href="/charlie/development/web/MapWeb/index.html">Maps</a></li>
	<li><a href="/charlie/development/web/Modernizr/index.html">Modernizr</a></li>
	<li><a href="/web-guide/CdnExplained.html">Online Code and CDN Explained</a></li>
	<li><a href="/charlie/development/web/Python/index.html">Python</a></li>
	<li><a href="/charlie/development/web/Php">PHP</a></li>
	<li><a href="/charlie/development/web/UnitTests">Unit Testing</a></li>
</ul>
