#! /usr/bin/env bash

TARGET=Isit322-Week09.md

sed -i 's|http://charliecalvert.github.io/books/CloudNotes/Isit322|/teach/isit322|g' $TARGET
sed -i 's|http://elvenware.com/charlie/books/CloudNotes/Isit322|/teach/isit322|g' $TARGET
sed -i 's|http://www.elvenware.com/charlie/development/android|/android-guide|g' $TARGET
sed -i 's|http://www.elvenware.com/charlie/Videos.html|/tools/Videos.html|g' $TARGET
sed -i 's|http://www.elvenware.com/charlie/os/linux|/os-guide/linux|g' $TARGET
sed -i 's|http://www.elvenware.com/charlie/development/cloud/Git.html|/git-guide|g' $TARGET
sed -i 's|http://www.ccalvert.net/books/CloudNotes/Assignments/React|/teach/assignments/react|g' $TARGET
sed -i 's|http://www.ccalvert.net/books/CloudNotes/Assignments|/teach/assignments|g' $TARGET
sed -i 's|http://www.elvenware.com/charlie/books/CloudNotes/Assignments|/teach/assignments|g' $TARGET
sed -i 's|http://elvenware.com/charlie/development/web/JavaScript|/javascript-guide|g' $TARGET
sed -i 's|http://www.elvenware.com/charlie/development/web/JavaScript|/javascript-guide|g' $TARGET
